### ISSUE TITLE
PyPI upload broken

### ISSUE THREAD

**Issue by OldhamMade** [wolever/pprintpp#16]
Latest PyPI upload (0.2.2) is missing the pprintpp module. `ls` of the .tar.gz file shows the following:
```
MANIFEST.in
PKG-INFO
README.rst
pprintpp.egg-info
setup.cfg
setup.py
```
And installs are therefore breaking.

**Comment by wolever** [comment]
D'oh! Thanks! I've just push'd 0.2.3 which fixes that.
