### ISSUE TITLE
Weird indent

### ISSUE THREAD

**Issue by rgarrigue** [wolever/pprintpp#17]
Hi

I got a kinda weird output from pprintpp. Here's the code, it's reading a java properties file and putting it in a "tree" data collection made with defaultdict

    # pip install -U pip pyjavaproperties pprintpp pp-ez

    from pyjavaproperties import Properties
    from collections import defaultdict
    import pp

    class tree(dict):
        def __missing__(self, key):
            value = self[key] = type(self)()
            return value

    p = Properties()
    p.load(open('my.properties'))

    data = tree()
    for name in p.propertyNames():
        if re.match('^tomcat\d.port',name):
           n = name.split('.')
           data[n[0]][n[2]] = p.getProperty(name)
           
    pp(data)

Here's a relevant piece of properties

    tomcat1.port.ajp13=53000
    tomcat1.port.http=52100
    tomcat1.port.jmx=52200
    tomcat1.port.shutdown=59000
    tomcat2.port.http=52020
    tomcat2.port.jmx=52320
    tomcat2.port.shutdown=59020
    tomcat3.port.http=52030
    tomcat3.port.jmx=52330
    tomcat3.port.shutdown=59030
    tomcat4.port.http=52040
    tomcat4.port.jmx=52340
    tomcat4.port.shutdown=59040
    tomcat5.port.http=52050
    tomcat5.port.jmx=52350
    tomcat5.port.shutdown=59050
    tomcat6.port.http=52060
    tomcat6.port.jmx=52360
    tomcat6.port.shutdown=59060

Here's the weird output

    {
        'tomcat1': {
            'ajp13': '53000',
            'http': '52100',
            'jmx': '52200',
            'shutdown': '59000',
        },
        'tomcat2': {'http': '52020', 'jmx': '52320', 'shutdown': '59020'},
        'tomcat3': {'http': '52030', 'jmx': '52330', 'shutdown': '59030'},
        'tomcat4': {'http': '52040', 'jmx': '52340', 'shutdown': '59040'},
        'tomcat5': {'http': '52050', 'jmx': '52350', 'shutdown': '59050'},
        'tomcat6': {'http': '52060', 'jmx': '52360', 'shutdown': '59060'},
    }

That's good enought for me, but still quite curious!

I'm running centos6's default Python 2.6.6 with pprintpp out of pip

**Comment by wolever** [comment]
This is happening because `pprintpp` will try to print containers on one line provided it won't be longer than 80 characters, but wrap all the elements if the line would be > 80 characters.

You can override this with the `width` argument.

**Comment by rgarrigue** [comment]
Understood, thanks !
